name: Build, Test, Publish to Nuget
on:
  push:
    branches:
      - master
    
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Build, test, pack & publish
    steps:
    - uses: actions/checkout@v3    
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Build
      run: dotnet build  --no-restore -c Release ./Wororo.Utilities/Wororo.Utilities.csproj
    - name: Pack
      run: dotnet pack  --no-build -c Release ./Wororo.Utilities/Wororo.Utilities.csproj -o .
    - name: Push Nuget
      run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ SECRETS.NUGET_API_KEY }} --skip-duplicate -n 1
    
